id: I95FD4CA9
default_language: zh
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-08 15:15:38.764460
last_modified: 2023-02-08 15:15:38.764561
source_metadata:
  title: 'PP: Prajñāpāramitāhṛdaya'
  language: zh
bases:
  4B66:
    base_file: 4B66.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
